### ISSUE TITLE
Z-index issue with tooltips and top menu separators on sankey

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/TRASE-frontend#412] opened 2017-05-24 13:12 UTC
![trasehover](https://cloud.githubusercontent.com/assets/973964/26404773/5fc1c566-4093-11e7-8308-b1ca881943de.gif)

**Comment by nerik** [comment] 2017-05-24 13:20
https://github.com/Vizzuality/TRASE-frontend/pull/399

**Comment by nerik** [comment] 2017-05-24 13:21
Duplicate of https://github.com/Vizzuality/TRASE-frontend/issues/391

**Closed as completed by nerik** 2017-05-24 13:21 UTC
Labels: tool, bug
